# Dependencies
#markdown:         redcarpet
#highlighter:      pygments
plugins:
    - jekyll-gist
    - jekyll-paginate
    - jekyll-feed
    - jekyll-sitemap

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Hex Fish
tagline:          ''
description:      ''
url:              http://0xf15h.github.io
baseurl:          /

author:
  name:           'Hex Fish'
  url:            https://twitter.com/0xf15h

paginate:         5
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/0xf15h
